config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :services do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/service.rb
class Service < ApplicationRecord
  CATEGORIES = ["Literary Translation", "Legal Translation", "Technical Translation", "Simultaneous Interpretation", "Consecutive Interpretation", "Over-the-phone Interpretation"]
  PRIMARY_LANGUAGE = ["English", "French", "German", "Spanish", "Italian", "Greek", "Arabic", "Turkish", "Polish", "Chinese", "Japanese" ]
  TYPES = ["Remote", "On-Site"]
  validates :category, inclusion: { in: CATEGORIES }
  validates :primary_language, inclusion: { in: PRIMARY_LANGUAGE }
  validates :type_of_service, inclusion: { in: TYPES }
  belongs_to :user
  geocoded_by :address, through: :users
  after_validation :geocode, if: :will_save_change_to_address?

  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :date_of_birth, :phone_number])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name, :date_of_birth, :phone_number])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]


  def index
    if params[:query].present?
      @query = params[:query]
      @services = Service.where("title ILIKE ?", "%#{params[:query]}%")
    else
      @services = Service.all
    end

    @markers = @services.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude
        image_url: helpers.asset_url("logo.png")
      }
    end
  end

  def show
    @service = Service.find(params[:id])
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to service_url(@service), notice: "Service was successfully created." }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @service = Service.find(params[:id])
    @service.destroy
    redirect_to services_path
  end

private

  def service_params
    params.require(:service).permit(:title, :category, :price, :description, :availability, :primary_language, :target_language, :photo, :training, :experience, :years_of_experience, :type_of_service)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TranslationIversen</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<body class="background">
  <div class="homeHeadContent">
    <div class="navbar navbar-expand-lg navbar-light">
      <div class="navbar-brand">
        <img src="<%= image_path "logo2" %>" alt="Iversen Logo" class="avatar-square">
      </div>
      <div class="d-flex justify-content-end navbar-buttons">
        <%= link_to 'Work with us!', new_service_path, :class => "nav-button-work" %>
        <% if user_signed_in? %>
        <div class="form-new">
        <%= current_user.email %>
        </div>
          <%= button_to 'SIGN OUT', destroy_user_session_path, method: 'delete', :class => "nav-button-iversen" %>
        <% else %>
          <%= link_to 'SIGN UP', new_user_registration_path, :class => "nav-button-iversen" %>
          <%= link_to 'LOGIN', new_user_session_path, :class => "nav-button-iversen" %>
        <% end %>
      </div>
    </div>
    <div class="overlay">
      <div id="container">
	      <div id="text"></div><div id="cursor"></div>
      </div>
      <div class="container-search-bar">
        <%= form_tag services_path, :class => "search-bar", method: :get do %>
         <%= text_field_tag :query,
         params[:query],
         class: "form-control search-input",
         placeholder: "What service do you need?"
         %>
         <%= submit_tag "Search", class: "nav-button-iversen" %>
        <% end %>
      </div>
    </div>


    <video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop" class="video-intro">
      <source src="<%= image_path "introvideo2.mp4" %>" type="video/mp4">
    </video>


    <div class="footer form-new justify-content-center">
      <div class="footer-links">
        <a href="https://github.com/Janek-92"><i class="fab fa-github"></i></a>
        <a href="https://linkedin.com/in/janek-iversen-10511786"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="footer-copyright">
        Translation & Interpretation Iversen (c) Copyright 2022
      </div>
    </div>
  </div>
</body>




  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script

app/views/services/index.html.erb
<body class="background-index">
  <div class="homeHeadContent">
    <div class="navbar navbar-expand-lg navbar-light">
      <div class="navbar-brand">
        <%= link_to root_path do %>
        <img src="<%= image_path "logo2" %>" alt="Iversen Logo" class="avatar-square">
        <% end %>
      </div>
      <div class="d-flex justify-content-end navbar-buttons">
        <%= link_to 'Work with us!', new_service_path, :class => "nav-button-work" %>
        <% if user_signed_in? %>
        <div class="form-new">
        <%= current_user.email %>
        </div>
          <%= link_to 'SIGN OUT', destroy_user_session_path, method: 'delete', :class => "nav-button-iversen" %>
        <% else %>
          <%= link_to 'SIGN UP', new_user_registration_path, :class => "nav-button-iversen" %>
          <%= link_to 'LOGIN', new_user_session_path, :class => "nav-button-iversen" %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="under-nav-breaker">
    <!-- Make space under navbar -->
  </div>

  <div class="container-number-items">
    <div class="text-center p-2">
      <div class="col">
        <% if @query %>
          <p>You searched for <strong><%= @query %></strong>. We found <%= @services.count %> services out of our <%= Service.count %> on our website.</p>
        <% else %>
          <p>All <%= Service.count %> services</p>
        <% end %>
      </div>
    </div>
  </div>

  <div class="cards" id="cards-container">
    <% @services.each do |service| %>
      <div class="item-card">
        <%= link_to  service_path(service) do %>
        <div class="item-card-image">
          <% if service.photo.key.nil? %>
          <% else %>
            <%= cl_image_tag service.photo.key, class: "item-avatar" %>
          <% end %>
        </div>
        <div class="card-item-content">
          <h2><%= service.user.last_name %></h2>
          <p><%= service.category %></p>
          <p> <strong><%= service.primary_language %> <-> <%= service.target_language %></strong></p>
        </div>
        <div class="card-item-pricing">
          <h2><%= service.price %> € / Hour</h2>
        </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div style="width: 100%; height: 600px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

  <h3 class="text-center"><%= link_to "Go back", root_path, :class => "btn btn-link" %></h3>
  <div class="footer form-new">
    <div class="footer">
      <a href="https://github.com/Janek-92"><i class="fab fa-github"></i></a>
      <a href="https://linkedin.com/in/janek-iversen-10511786"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      Translation & Interpretation Iversen (c) Copyright 2022
    </div>
  </div>
</body>

app/views/services/new.html.erb
<body class="background">
  <div class="homeHeadContent">
    <div class="navbar navbar-expand-lg navbar-light">
      <div class="navbar-brand">
        <%= link_to root_path do %>
        <%= image_tag "logo2.png", class:"avatar-square" %>
      </div>
      <div class="d-flex justify-content-end navbar-buttons">
        <% if user_signed_in? %>
        <%= current_user.email %>
          <%= link_to 'SIGN OUT', destroy_user_session_path, method: 'delete', :class => "nav-button-iversen" %>
        <% else %>
          <%= link_to 'SIGN UP', new_user_registration_path, :class => "nav-button-iversen" %>
          <%= link_to 'LOGIN', new_user_session_path, :class => "nav-button-iversen" %>
        <% end %>
      </div>
    </div>
  </div>


  <div class="container py-5">
    <div class="row form-new">
      <div class="form-upload shadow-sm p-3 mb-5 bordered col-12 col-md-6 offset-lg-3 justify-content-center p-5" style="background-color: #354558">
        <div class="shadow-md rounded px-8 pt-6 pb-8 mb-4">
          <div class="centered"> <h2>Tell us about yourself!</h2></div>
              <%= simple_form_for(@service) do |f| %>
                <%= f.input :title, placeholder: "Name your service", class: "form-inputs" %>
                <%= f.input :category, collection: Service::CATEGORIES, placeholder: "What's the category?", :class => "input-field" %>
                <%= f.input :primary_language, collection: Service::PRIMARY_LANGUAGE, placeholder: "What is your primary language?", :class => "input-field" %>
                <%= f.input :target_language, collection: Service::PRIMARY_LANGUAGE, placeholder: "What is your target language?", :class => "input-field" %>
                <p>Do you have other combinations?</p>
                <%= f.input :primary_language, collection: Service::PRIMARY_LANGUAGE, placeholder: "What is your primary language?", :class => "input-field" %>
                <%= f.input :target_language, collection: Service::PRIMARY_LANGUAGE, placeholder: "What is your target language?", :class => "input-field" %>
                <%= f.input :training, placeholder: "What training have you received?", :class => "input-field" %>
                <%= f.input :experience, placeholder: "Tell us about your past experience in this field", :class => "input-field" %>
                <%= f.input :years_of_experience, placeholder: "How many years of experience do you have?", :class => "input-field" %>
                <%= f.input :type_of_service, collection: Service::TYPES, placeholder: "What service do you want to offer?", :class => "input-field" %>
                <%= f.input :price, placeholder: "What's your hourly rate?", :class => "input-field" %>
                <%= f.input :description, placeholder: "Provide some more info!", :class => "input-field" %>
                <%= f.input :availability, :class => "input-field" %>
                <%= f.input :photo, as: :file, :class => "input-field" %>
                <div>
                  <p class="text-center text-gray-500 text-xs">
                  Make sure that all information is correct!
                  </p>
                </div>
                <div class="d-grid gap-2 col-6 mx-auto justify-content-center">
                  <div class="form-actions nav-button-iversen">
                    <%= f.button :submit, "Upload" %>
                  </div>
                </div>
                <div class="centered">
                  <%= link_to 'Back', services_path %>
                </div>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>
<div class="footer form-new">
    <div class="footer">
      <a href="https://github.com/Janek-92"><i class="fab fa-github"></i></a>
      <a href="https://linkedin.com/in/janek-iversen-10511786"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      Translation & Interpretation Iversen (c) Copyright 2022
    </div>
</div>

app/views/services/show.html.erb
<body class="background-show">
  <div class="homeHeadContent">
    <div class="navbar navbar-expand-lg navbar-light">
      <div class="navbar-brand">
        <%= link_to root_path do %>
        <img src="<%= image_path "logo2" %>" alt="Iversen Logo" class="avatar-square">
        <% end %>
      </div>
      <div class="d-flex justify-content-end navbar-buttons">
        <%= link_to 'Work with us!', new_service_path, :class => "nav-button-work" %>
        <% if user_signed_in? %>
        <div class="form-new">
        <%= current_user.email %>
        </div>
          <%= link_to 'SIGN OUT', destroy_user_session_path, method: 'delete', :class => "nav-button-iversen" %>
        <% else %>
          <%= link_to 'SIGN UP', new_user_registration_path, :class => "nav-button-iversen" %>
          <%= link_to 'LOGIN', new_user_session_path, :class => "nav-button-iversen" %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="container py-5">
    <div class="row login-form">
      <div class="form-upload shadow-sm p-3 mb-5 bordered col-12 col-md-6 offset-lg-3 justify-content-center" style="background-color: #354558">
        <div class="shadow-md rounded px-8 pt-6 pb-8 mb-4">
          <div class="centered">
            <div class="item-card-image">
              <% if @service.photo.key.nil? %>
              <% else %>
                <%= cl_image_tag @service.photo.key, class: "item-avatar" %>
              <% end %>
            </div>
            <h2><%= @service.category %></h2>
            <h3>Name:<%= @service.user.last_name %></h3>
            <p><%= @service.primary_language %> <-> <%= @service.target_language %></p>
            <p>Price:<%= @service.price %> € / Hour</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container contact-form">
    <form method="post">
        <h3>Contact Me</h3>
       <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <input type="text" name="txtName" class="form-control" placeholder="Your Name *" value="" />
                </div>
                <div class="form-group">
                    <input type="text" name="txtEmail" class="form-control" placeholder="Your Email *" value="" />
                </div>
                <div class="form-group">
                    <input type="text" name="txtPhone" class="form-control" placeholder="Your Phone Number *" value="" />
                </div>
                <div class="form-group">
                    <input type="submit" name="btnSubmit" class="btnContact" value="Send Message" />
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <textarea name="txtMsg" class="form-control" placeholder="How can I help you? *" style="width: 100%; height: 150px;"></textarea>
                </div>
            </div>
        </div>
    </form>
  </div>
</body>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>